# Generated by Django 3.1.3 on 2020-11-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeapp', '0002_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
